var DeviceType={SENSOR:0,EFFECTOR:1,EVENT:2,COMMAND:3},DataType={INTEGER:4,FLOAT:5,STRING:6},ConnectionState={CONNECTING:1,CONNECTED:2,CONNECTION_LOST:3,DISCONNECTED:4,CLOSED:5};
function Device(a,x,m,p,d,l,t,y,q){var n=this,r={read:void 0,write:void 0},B=m,f=!1,k=!1,A=[];if(0<l)for(r.read=Array(l),r.write=Array(l),m=0;m<l;++m)r.read[m]=q,r.write[m]=q;a.bind(n,p,r,{fire:function(){k=!0},update:function(){f=k;k=!1},notifyDeviceDataChanged:function(){for(var a in A)A[a](n,r.read)},reset:function(){k=f=!1;if(0<l)for(var a=0;a<l;++a)r.read[a]=q,r.write[a]=q;else r.read=void 0,r.write=void 0}});n.getId=function(){return x&4293922815};n.getName=function(){return B};n.setName=function(a){B=
""+a};n.getDeviceType=function(){return p};n.getDataType=function(){return d};n.getDataSize=function(){return l};n.e=function(){return f};var w=function(a){return d==DataType.INTEGER||d==DataType.FLOAT?"number"==typeof a:d==DataType.STRING?"string"==typeof a:!1};n.read=function(a){var c=r.read;if("number"==typeof a)return a=parseInt(a),0>a||void 0==c||a>=c.length?d==DataType.STRING?"":0:c[a];if(a&&a.constructor==Array){var f=a.length;if(0>=f||void 0==c)return d==DataType.STRING?"":0;for(var f=Math.min(c.length,
f),k=0;k<f;++k)a[k]=c[k];return f}return void 0==c||0>=c.length?d==DataType.STRING?"":0:c[0]};n.write=function(c,f){if(p==DeviceType.SENSOR||p==DeviceType.EVENT)return!1;var h=r.write;if("number"!=typeof c||"number"!=typeof f&&"string"!=typeof f){if(c&&c.constructor==Array){var d=c.length;if(0>=d)return 0;0>l&&(void 0==h||h.length!=d)&&(h=r.write=Array(d));if(void 0==h)return 0;var b=h.length;if(0>=b)return 0;b=Math.min(b,d);for(d=0;d<b;++d){var e=c[d];w(e)&&("number"==typeof e&&(e<t?e=t:e>y&&(e=
y)),h[d]=e,k=!0)}if(a)a.onMotoringDeviceWritten(n);return b}if("number"==typeof c||"string"==typeof c){if(0==w(c))return!1;if(void 0==h||0>=h.length)if(0>l)h=r.write=Array(1);else return!1;"number"==typeof c&&(c<t?c=t:c>y&&(c=y));h[0]=c;k=!0;if(a)a.onMotoringDeviceWritten(n);return!0}return!1}e=parseInt(c);if(0>e||0==w(f))return!1;if(void 0==h)if(0>l)for(h=r.write=Array(e+1),d=0;d<e;++d)h[d]=q;else return!1;else if(e>=h.length)if(0>l){var u=Array(e+1);b=h.length;for(d=0;d<b;++d)u[d]=h[d];for(d=b;d<
e;++d)u[d]=q;h=r.write=u}else return!1;"number"==typeof f&&(f<t?f=t:f>y&&(f=y));h[e]=f;k=!0;if(a)a.onMotoringDeviceWritten(n);return!0};n.addDeviceDataChangedListener=function(a){"function"==typeof a&&A.push(a)};n.removeDeviceDataChangedListener=function(a){"function"==typeof a&&(a=A.indexOf(a),0<=a&&A.splice(a,1))};n.clearDeviceDataChangedListeners=function(){A=[]}}
function __Runner(){var a={},x={},m={},p=void 0,d=!1,l=!1,t=!1,y=!1,q=function(){a={};x={};m={};y=t=!1};this.addRobot=function(d,l,p){var f=d.getId();var k=0;for(var n in a)f==a[n].getId()&&++k;n=f+k;l.model=f;l.index=k;a[n]=d;x[n]=l;m[n]=p;return k};this.open=function(n,r,B){if("WebSocket"in window)try{var f=new WebSocket(n);f.binaryType="arraybuffer";p=f;f.onopen=function(){r&&"function"==typeof r&&r();f.onmessage=function(a){try{var c=JSON.parse(a.data),d=m[c.model+c.index];d&&(d.handleSensory(c),
t=!0)}catch(v){}};f.onclose=function(){d=!1;B&&"function"==typeof B&&B()};Date.now||(Date.now=function(){return(new Date).getTime()});var k=Date.now(),n=function(){if(d&&p){if(Date.now()>k){try{if(l){for(var f in m)m[f].updateSensory();if(t&&window.execute)try{window.execute()}catch(v){}for(f in m)m[f].updateMotoring(),m[f].requestMotoring()}if(y){y=!1;for(var c in a)a[c].reset();for(f in m)m[f].requestMotoring();var h=JSON.stringify(x);d&&p&&p.send(h);q()}else h=JSON.stringify(x),d&&p&&p.send(h)}catch(v){}k+=
20}setTimeout(n,5)}};d=!0;n()};return!0}catch(k){}return!1};this.close=function(){d=!1;p&&(p.close(),p=void 0)};this.start=function(){q();l=!0};this.stop=function(){l=!1;y=!0}}var __runner=new __Runner,execute=void 0,__timeouts=[],__intervals=[];window.__setTimeout=function(a,x){var m=setTimeout(a,x);__timeouts.push(m)};window.__setInterval=function(a,x){var m=setInterval(a,x);__intervals.push(m)};
function connect(a,x,m){a&&(0>a.indexOf(":")?__runner.open("ws://"+a+":58000",x,m):__runner.open("ws://"+a,x,m),__runner.start())}function disconnect(){stopCode();__runner.close()}function runCode(a){__runner.start();a=a.replace(/setTimeout/gi,"__setTimeout");a=a.replace(/setInterval/gi,"__setInterval");eval(a+"if(execute && typeof execute == 'function') { window.execute = execute; }")}
function stopCode(){window.execute=void 0;__runner.stop();for(var a in __timeouts)clearTimeout(__timeouts[a]);__timeouts=[];for(a in __intervals)clearInterval(__intervals[a]);__intervals=[]}
function Hamster(){var a=this,x="Hamster",m=void 0,p=0,d=0,l=0,t=void 0,y=[],q=[],n=[],r=[],B=[],f=[],k=[],A=ConnectionState.CONNECTING,w=0,c={bind:function(a,e,c,d){e==DeviceType.SENSOR||e==DeviceType.EVENT?(y.push(a),q.push(c.read),n.push(d)):(r.push(a),B.push(c.read),f.push(c.write),k.push(d))},onMotoringDeviceWritten:function(a){switch(a.getId()){case Hamster.TOPOLOGY:w|=33554432;break;case Hamster.LEFT_LED:w|=16777216;break;case Hamster.RIGHT_LED:w|=8388608;break;case Hamster.NOTE:w|=4194304;
break;case Hamster.LINE_TRACER_MODE:w|=2097152;break;case Hamster.LINE_TRACER_SPEED:w|=1048576;break;case Hamster.IO_MODE_A:w|=524288;break;case Hamster.IO_MODE_B:w|=262144;break;case Hamster.CONFIG_PROXIMITY:w|=131072;break;case Hamster.CONFIG_GRAVITY:w|=65536;break;case Hamster.CONFIG_BAND_WIDTH:w|=32768}}},h={};h[Hamster.LEFT_WHEEL]=new Device(c,Hamster.LEFT_WHEEL,"LeftWheel",DeviceType.EFFECTOR,DataType.INTEGER,1,-100,100,0);h[Hamster.RIGHT_WHEEL]=new Device(c,Hamster.RIGHT_WHEEL,"RightWheel",
DeviceType.EFFECTOR,DataType.INTEGER,1,-100,100,0);h[Hamster.BUZZER]=new Device(c,Hamster.BUZZER,"Buzzer",DeviceType.EFFECTOR,DataType.FLOAT,1,0,167772.15,0);h[Hamster.OUTPUT_A]=new Device(c,Hamster.OUTPUT_A,"OutputA",DeviceType.EFFECTOR,DataType.INTEGER,1,0,255,0);h[Hamster.OUTPUT_B]=new Device(c,Hamster.OUTPUT_B,"OutputB",DeviceType.EFFECTOR,DataType.INTEGER,1,0,255,0);h[Hamster.TOPOLOGY]=new Device(c,Hamster.TOPOLOGY,"Topology",DeviceType.COMMAND,DataType.INTEGER,1,0,15,0);h[Hamster.LEFT_LED]=
new Device(c,Hamster.LEFT_LED,"LeftLed",DeviceType.COMMAND,DataType.INTEGER,1,0,7,0);h[Hamster.RIGHT_LED]=new Device(c,Hamster.RIGHT_LED,"RightLed",DeviceType.COMMAND,DataType.INTEGER,1,0,7,0);h[Hamster.NOTE]=new Device(c,Hamster.NOTE,"Note",DeviceType.COMMAND,DataType.INTEGER,1,0,88,0);h[Hamster.LINE_TRACER_MODE]=new Device(c,Hamster.LINE_TRACER_MODE,"LineTracerMode",DeviceType.COMMAND,DataType.INTEGER,1,0,15,0);h[Hamster.LINE_TRACER_SPEED]=new Device(c,Hamster.LINE_TRACER_SPEED,"LineTracerSpeed",
DeviceType.COMMAND,DataType.INTEGER,1,1,8,5);h[Hamster.IO_MODE_A]=new Device(c,Hamster.IO_MODE_A,"IoModeA",DeviceType.COMMAND,DataType.INTEGER,1,0,15,0);h[Hamster.IO_MODE_B]=new Device(c,Hamster.IO_MODE_B,"IoModeB",DeviceType.COMMAND,DataType.INTEGER,1,0,15,0);h[Hamster.CONFIG_PROXIMITY]=new Device(c,Hamster.CONFIG_PROXIMITY,"ConfigProximity",DeviceType.COMMAND,DataType.INTEGER,1,1,7,2);h[Hamster.CONFIG_GRAVITY]=new Device(c,Hamster.CONFIG_GRAVITY,"ConfigGravity",DeviceType.COMMAND,DataType.INTEGER,
1,0,3,0);h[Hamster.CONFIG_BAND_WIDTH]=new Device(c,Hamster.CONFIG_BAND_WIDTH,"ConfigBandWidth",DeviceType.COMMAND,DataType.INTEGER,1,1,8,3);h[Hamster.SIGNAL_STRENGTH]=new Device(c,Hamster.SIGNAL_STRENGTH,"SignalStrength",DeviceType.SENSOR,DataType.INTEGER,1,-128,0,0);h[Hamster.LEFT_PROXIMITY]=new Device(c,Hamster.LEFT_PROXIMITY,"LeftProximity",DeviceType.SENSOR,DataType.INTEGER,1,0,255,0);h[Hamster.RIGHT_PROXIMITY]=new Device(c,Hamster.RIGHT_PROXIMITY,"RightProximity",DeviceType.SENSOR,DataType.INTEGER,
1,0,255,0);h[Hamster.LEFT_FLOOR]=new Device(c,Hamster.LEFT_FLOOR,"LeftFloor",DeviceType.SENSOR,DataType.INTEGER,1,0,255,0);h[Hamster.RIGHT_FLOOR]=new Device(c,Hamster.RIGHT_FLOOR,"RightFloor",DeviceType.SENSOR,DataType.INTEGER,1,0,255,0);h[Hamster.ACCELERATION]=new Device(c,Hamster.ACCELERATION,"Acceleration",DeviceType.SENSOR,DataType.INTEGER,3,-32768,32767,0);h[Hamster.LIGHT]=new Device(c,Hamster.LIGHT,"Light",DeviceType.SENSOR,DataType.INTEGER,1,0,65535,0);h[Hamster.TEMPERATURE]=new Device(c,Hamster.TEMPERATURE,
"Temperature",DeviceType.SENSOR,DataType.INTEGER,1,-40,88,0);h[Hamster.INPUT_A]=new Device(c,Hamster.INPUT_A,"InputA",DeviceType.SENSOR,DataType.INTEGER,1,0,255,0);h[Hamster.INPUT_B]=new Device(c,Hamster.INPUT_B,"InputB",DeviceType.SENSOR,DataType.INTEGER,1,0,255,0);h[Hamster.LINE_TRACER_STATE]=new Device(c,Hamster.LINE_TRACER_STATE,"LineTracerState",DeviceType.EVENT,DataType.INTEGER,1,0,255,0);var v={map:0,leftWheel:0,rightWheel:0,buzzer:0,outputA:0,outputB:0,topology:0,leftLed:0,rightLed:0,note:0,
lineTracerMode:0,lineTracerSpeed:5,ioModeA:0,ioModeB:0,configProximity:2,configGravity:0,configBandWidth:3};a.getId=function(){return"kr.robomation.physical.hamster"};var z=__runner.addRobot(a,v,{handleSensory:function(b){A=b.connectionState;var e=b.map;q[0][0]=b.signalStrength;q[1][0]=b.leftProximity;q[2][0]=b.rightProximity;q[3][0]=b.leftFloor;q[4][0]=b.rightFloor;q[5][0]=b.accelerationX;q[5][1]=b.accelerationY;q[5][2]=b.accelerationZ;q[6][0]=b.light;q[7][0]=b.temperature;q[8][0]=b.inputA;q[9][0]=
b.inputB;var c;for(c=0;10>c;++c)n[c].fire();e&16&&(q[10][0]=b.lineTracerState,n[10].fire());for(c=0;10>c;++c)n[c].notifyDeviceDataChanged();e&16&&(n[10].notifyDeviceDataChanged(),64==b.lineTracerState&&(a.write(Hamster.LINE_TRACER_MODE,0),e=m,m=void 0,e&&e()));if(1==p)switch(d){case 1:2>l?(50>b.leftFloor&&50>b.rightFloor?l++:l=0,b=b.leftFloor-b.rightFloor,a.write(Hamster.LEFT_WHEEL,45+.25*b),a.write(Hamster.RIGHT_WHEEL,45-.25*b)):(l=0,d=2);break;case 2:10>l?(l++,b=b.leftFloor-b.rightFloor,a.write(Hamster.LEFT_WHEEL,
45+.25*b),a.write(Hamster.RIGHT_WHEEL,45-.25*b)):(a.write(Hamster.LEFT_WHEEL,0),a.write(Hamster.RIGHT_WHEEL,0),l=d=p=0,e=t,t=void 0,e&&e())}else if(2==p)switch(d){case 1:2>l?50<b.leftFloor&&l++:(l=0,d=2);break;case 2:20>b.leftFloor&&(d=3);break;case 3:2>l?20>b.leftFloor&&l++:(l=0,d=4);break;case 4:50<b.leftFloor&&(d=5);break;case 5:b=b.leftFloor-b.rightFloor,-15<b?(a.write(Hamster.LEFT_WHEEL,0),a.write(Hamster.RIGHT_WHEEL,0),l=d=p=0,e=t,t=void 0,e&&e()):(a.write(Hamster.LEFT_WHEEL,.5*b),a.write(Hamster.RIGHT_WHEEL,
.5*-b))}else if(3==p)switch(d){case 1:2>l?50<b.rightFloor&&l++:(l=0,d=2);break;case 2:20>b.rightFloor&&(d=3);break;case 3:2>l?20>b.rightFloor&&l++:(l=0,d=4);break;case 4:50<b.rightFloor&&(d=5);break;case 5:b=b.rightFloor-b.leftFloor,-15<b?(a.write(Hamster.LEFT_WHEEL,0),a.write(Hamster.RIGHT_WHEEL,0),l=d=p=0,e=t,t=void 0,e&&e()):(a.write(Hamster.LEFT_WHEEL,.5*-b),a.write(Hamster.RIGHT_WHEEL,.5*b))}},requestMotoring:function(){var a=4227858432|w;w=0;v.map=a;v.leftWheel=f[0][0];v.rightWheel=f[1][0];
v.buzzer=f[2][0];v.outputA=f[3][0];v.outputB=f[4][0];a&33554432&&(v.topology=f[5][0]);a&16777216&&(v.leftLed=f[6][0]);a&8388608&&(v.rightLed=f[7][0]);a&4194304&&(v.note=f[8][0]);a&2097152&&(v.lineTracerMode=f[9][0]);a&1048576&&(v.lineTracerSpeed=f[10][0]);a&524288&&(v.ioModeA=f[11][0]);a&262144&&(v.ioModeB=f[12][0]);a&131072&&(v.configProximity=f[13][0]);a&65536&&(v.configGravity=f[14][0]);a&32768&&(v.configBandWidth=f[15][0])},updateSensory:function(){for(var a in n)n[a].update()},updateMotoring:function(){for(var a in k)k[a].update()}});
a.getIndex=function(){return z};a.getName=function(){return x};a.setName=function(a){x=""+a};a.findDeviceById=function(a){if(a=h[a])return a};a.e=function(b){return(b=a.findDeviceById(b))?b.e():!1};a.read=function(b,e){var c=a.findDeviceById(b);return c?c.read(e):0};a.write=function(b,c,d){return(b=a.findDeviceById(b))?b.write(c,d):c&&c.constructor==Array?0:!1};a.addDeviceDataChangedListener=function(a){for(var b in h)h[b].addDeviceDataChangedListener(a)};a.removeDeviceDataChangedListener=function(a){for(var b in h)h[b].removeDeviceDataChangedListener(a)};
a.clearDeviceDataChangedListeners=function(){for(var a in h)h[a].clearDeviceDataChangedListeners()};a.reset=function(){var a=k,c;for(c in a)a[c].reset();a=n;for(c in a)a[c].reset();w|=67076096;m=void 0;l=d=p=0;t=void 0};a.connectionState=function(){return A};a.wheels=function(b,c){a.write(Hamster.LINE_TRACER_MODE,0);"number"==typeof b&&a.write(Hamster.LEFT_WHEEL,b);"number"==typeof c?a.write(Hamster.RIGHT_WHEEL,c):"number"==typeof b&&a.write(Hamster.RIGHT_WHEEL,b)};a.leftWheel=function(b){a.write(Hamster.LINE_TRACER_MODE,
0);"number"==typeof b&&a.write(Hamster.LEFT_WHEEL,b)};a.rightWheel=function(b){a.write(Hamster.LINE_TRACER_MODE,0);"number"==typeof b&&a.write(Hamster.RIGHT_WHEEL,b)};a.stop=function(){a.write(Hamster.LINE_TRACER_MODE,0);a.write(Hamster.LEFT_WHEEL,0);a.write(Hamster.RIGHT_WHEEL,0)};a.lineTracerMode=function(b,c){a.write(Hamster.LEFT_WHEEL,0);a.write(Hamster.RIGHT_WHEEL,0);if("number"==typeof b){switch(b){case Hamster.LINE_TRACER_MODE_BLACK_TURN_LEFT:case Hamster.LINE_TRACER_MODE_BLACK_TURN_RIGHT:case Hamster.LINE_TRACER_MODE_BLACK_MOVE_FORWARD:case Hamster.LINE_TRACER_MODE_BLACK_UTURN:case Hamster.LINE_TRACER_MODE_WHITE_TURN_LEFT:case Hamster.LINE_TRACER_MODE_WHITE_TURN_RIGHT:case Hamster.LINE_TRACER_MODE_WHITE_MOVE_FORWARD:case Hamster.LINE_TRACER_MODE_WHITE_UTURN:c&&
"function"==typeof c&&(m=c)}a.write(Hamster.LINE_TRACER_MODE,b)}};a.lineTracerSpeed=function(b){"number"==typeof b&&a.write(Hamster.LINE_TRACER_SPEED,b)};a.boardForward=function(b){"function"==typeof b&&(t=b);d=1;l=0;p=1;a.write(Hamster.LINE_TRACER_MODE,0);a.write(Hamster.LEFT_WHEEL,45);a.write(Hamster.RIGHT_WHEEL,45)};a.boardLeft=function(b){"function"==typeof b&&(t=b);d=1;l=0;p=2;a.write(Hamster.LINE_TRACER_MODE,0);a.write(Hamster.LEFT_WHEEL,-45);a.write(Hamster.RIGHT_WHEEL,45)};a.boardRight=function(b){"function"==
typeof b&&(t=b);d=1;l=0;p=3;a.write(Hamster.LINE_TRACER_MODE,0);a.write(Hamster.LEFT_WHEEL,45);a.write(Hamster.RIGHT_WHEEL,-45)};a.leds=function(b,c){"number"==typeof b&&a.write(Hamster.LEFT_LED,b);"number"==typeof c?a.write(Hamster.RIGHT_LED,c):"number"==typeof b&&a.write(Hamster.RIGHT_LED,b)};a.leftLed=function(b){"number"==typeof b&&a.write(Hamster.LEFT_LED,b)};a.rightLed=function(b){"number"==typeof b&&a.write(Hamster.RIGHT_LED,b)};a.buzzer=function(b){"number"==typeof b&&a.write(Hamster.BUZZER,
b);a.write(Hamster.NOTE,0)};a.note=function(b){a.write(Hamster.BUZZER,0);"number"==typeof b&&a.write(Hamster.NOTE,b)};a.ioModeA=function(b){"number"==typeof b&&a.write(Hamster.IO_MODE_A,b)};a.ioModeB=function(b){"number"==typeof b&&a.write(Hamster.IO_MODE_B,b)};a.outputA=function(b){"number"==typeof b&&a.write(Hamster.OUTPUT_A,b)};a.outputB=function(b){"number"==typeof b&&a.write(Hamster.OUTPUT_B,b)};a.signalStrength=function(){return a.read(Hamster.SIGNAL_STRENGTH)};a.leftProximity=function(){return a.read(Hamster.LEFT_PROXIMITY)};
a.rightProximity=function(){return a.read(Hamster.RIGHT_PROXIMITY)};a.leftFloor=function(){return a.read(Hamster.LEFT_FLOOR)};a.rightFloor=function(){return a.read(Hamster.RIGHT_FLOOR)};a.accelerationX=function(){return a.read(Hamster.ACCELERATION,0)};a.accelerationY=function(){return a.read(Hamster.ACCELERATION,1)};a.accelerationZ=function(){return a.read(Hamster.ACCELERATION,2)};a.light=function(){return a.read(Hamster.LIGHT)};a.temperature=function(){return a.read(Hamster.TEMPERATURE)};a.inputA=
function(){return a.read(Hamster.INPUT_A)};a.inputB=function(){return a.read(Hamster.INPUT_B)}}Hamster.ID="kr.robomation.physical.hamster";Hamster.LEFT_WHEEL=4194304;Hamster.RIGHT_WHEEL=4194305;Hamster.BUZZER=4194306;Hamster.OUTPUT_A=4194307;Hamster.OUTPUT_B=4194308;Hamster.TOPOLOGY=4194309;Hamster.LEFT_LED=4194310;Hamster.RIGHT_LED=4194311;Hamster.NOTE=4194312;Hamster.LINE_TRACER_MODE=4194313;Hamster.LINE_TRACER_SPEED=4194314;Hamster.IO_MODE_A=4194315;Hamster.IO_MODE_B=4194316;
Hamster.CONFIG_PROXIMITY=4194317;Hamster.CONFIG_GRAVITY=4194318;Hamster.CONFIG_BAND_WIDTH=4194319;Hamster.SIGNAL_STRENGTH=4194320;Hamster.LEFT_PROXIMITY=4194321;Hamster.RIGHT_PROXIMITY=4194322;Hamster.LEFT_FLOOR=4194323;Hamster.RIGHT_FLOOR=4194324;Hamster.ACCELERATION=4194325;Hamster.LIGHT=4194326;Hamster.TEMPERATURE=4194327;Hamster.INPUT_A=4194328;Hamster.INPUT_B=4194329;Hamster.LINE_TRACER_STATE=4194330;Hamster.TOPOLOGY_NONE=0;Hamster.TOPOLOGY_DAISY_CHAIN=1;Hamster.TOPOLOGY_STAR=2;
Hamster.TOPOLOGY_EXTENDED_STAR=3;Hamster.LED_OFF=0;Hamster.LED_BLUE=1;Hamster.LED_GREEN=2;Hamster.LED_CYAN=3;Hamster.LED_RED=4;Hamster.LED_MAGENTA=5;Hamster.LED_YELLOW=6;Hamster.LED_WHITE=7;Hamster.LINE_TRACER_MODE_OFF=0;Hamster.LINE_TRACER_MODE_BLACK_LEFT_SENSOR=1;Hamster.LINE_TRACER_MODE_BLACK_RIGHT_SENSOR=2;Hamster.LINE_TRACER_MODE_BLACK_BOTH_SENSORS=3;Hamster.LINE_TRACER_MODE_BLACK_TURN_LEFT=4;Hamster.LINE_TRACER_MODE_BLACK_TURN_RIGHT=5;Hamster.LINE_TRACER_MODE_BLACK_MOVE_FORWARD=6;
Hamster.LINE_TRACER_MODE_BLACK_UTURN=7;Hamster.LINE_TRACER_MODE_WHITE_LEFT_SENSOR=8;Hamster.LINE_TRACER_MODE_WHITE_RIGHT_SENSOR=9;Hamster.LINE_TRACER_MODE_WHITE_BOTH_SENSORS=10;Hamster.LINE_TRACER_MODE_WHITE_TURN_LEFT=11;Hamster.LINE_TRACER_MODE_WHITE_TURN_RIGHT=12;Hamster.LINE_TRACER_MODE_WHITE_MOVE_FORWARD=13;Hamster.LINE_TRACER_MODE_WHITE_UTURN=14;Hamster.IO_MODE_ANALOG_INPUT=0;Hamster.IO_MODE_DIGITAL_INPUT=1;Hamster.IO_MODE_SERVO_OUTPUT=8;Hamster.IO_MODE_PWM_OUTPUT=9;
Hamster.IO_MODE_DIGITAL_OUTPUT=10;Hamster.NOTE_OFF=0;Hamster.NOTE_A_0=1;Hamster.NOTE_A_SHARP_0=2;Hamster.NOTE_B_FLAT_0=2;Hamster.NOTE_B_0=3;Hamster.NOTE_C_1=4;Hamster.NOTE_C_SHARP_1=5;Hamster.NOTE_D_FLAT_1=5;Hamster.NOTE_D_1=6;Hamster.NOTE_D_SHARP_1=7;Hamster.NOTE_E_FLAT_1=7;Hamster.NOTE_E_1=8;Hamster.NOTE_F_1=9;Hamster.NOTE_F_SHARP_1=10;Hamster.NOTE_G_FLAT_1=10;Hamster.NOTE_G_1=11;Hamster.NOTE_G_SHARP_1=12;Hamster.NOTE_A_FLAT_1=12;Hamster.NOTE_A_1=13;Hamster.NOTE_A_SHARP_1=14;
Hamster.NOTE_B_FLAT_1=14;Hamster.NOTE_B_1=15;Hamster.NOTE_C_2=16;Hamster.NOTE_C_SHARP_2=17;Hamster.NOTE_D_FLAT_2=17;Hamster.NOTE_D_2=18;Hamster.NOTE_D_SHARP_2=19;Hamster.NOTE_E_FLAT_2=19;Hamster.NOTE_E_2=20;Hamster.NOTE_F_2=21;Hamster.NOTE_F_SHARP_2=22;Hamster.NOTE_G_FLAT_2=22;Hamster.NOTE_G_2=23;Hamster.NOTE_G_SHARP_2=24;Hamster.NOTE_A_FLAT_2=24;Hamster.NOTE_A_2=25;Hamster.NOTE_A_SHARP_2=26;Hamster.NOTE_B_FLAT_2=26;Hamster.NOTE_B_2=27;Hamster.NOTE_C_3=28;Hamster.NOTE_C_SHARP_3=29;
Hamster.NOTE_D_FLAT_3=29;Hamster.NOTE_D_3=30;Hamster.NOTE_D_SHARP_3=31;Hamster.NOTE_E_FLAT_3=31;Hamster.NOTE_E_3=32;Hamster.NOTE_F_3=33;Hamster.NOTE_F_SHARP_3=34;Hamster.NOTE_G_FLAT_3=34;Hamster.NOTE_G_3=35;Hamster.NOTE_G_SHARP_3=36;Hamster.NOTE_A_FLAT_3=36;Hamster.NOTE_A_3=37;Hamster.NOTE_A_SHARP_3=38;Hamster.NOTE_B_FLAT_3=38;Hamster.NOTE_B_3=39;Hamster.NOTE_C_4=40;Hamster.NOTE_C_SHARP_4=41;Hamster.NOTE_D_FLAT_4=41;Hamster.NOTE_D_4=42;Hamster.NOTE_D_SHARP_4=43;Hamster.NOTE_E_FLAT_4=43;
Hamster.NOTE_E_4=44;Hamster.NOTE_F_4=45;Hamster.NOTE_F_SHARP_4=46;Hamster.NOTE_G_FLAT_4=46;Hamster.NOTE_G_4=47;Hamster.NOTE_G_SHARP_4=48;Hamster.NOTE_A_FLAT_4=48;Hamster.NOTE_A_4=49;Hamster.NOTE_A_SHARP_4=50;Hamster.NOTE_B_FLAT_4=50;Hamster.NOTE_B_4=51;Hamster.NOTE_C_5=52;Hamster.NOTE_C_SHARP_5=53;Hamster.NOTE_D_FLAT_5=53;Hamster.NOTE_D_5=54;Hamster.NOTE_D_SHARP_5=55;Hamster.NOTE_E_FLAT_5=55;Hamster.NOTE_E_5=56;Hamster.NOTE_F_5=57;Hamster.NOTE_F_SHARP_5=58;Hamster.NOTE_G_FLAT_5=58;
Hamster.NOTE_G_5=59;Hamster.NOTE_G_SHARP_5=60;Hamster.NOTE_A_FLAT_5=60;Hamster.NOTE_A_5=61;Hamster.NOTE_A_SHARP_5=62;Hamster.NOTE_B_FLAT_5=62;Hamster.NOTE_B_5=63;Hamster.NOTE_C_6=64;Hamster.NOTE_C_SHARP_6=65;Hamster.NOTE_D_FLAT_6=65;Hamster.NOTE_D_6=66;Hamster.NOTE_D_SHARP_6=67;Hamster.NOTE_E_FLAT_6=67;Hamster.NOTE_E_6=68;Hamster.NOTE_F_6=69;Hamster.NOTE_F_SHARP_6=70;Hamster.NOTE_G_FLAT_6=70;Hamster.NOTE_G_6=71;Hamster.NOTE_G_SHARP_6=72;Hamster.NOTE_A_FLAT_6=72;Hamster.NOTE_A_6=73;
Hamster.NOTE_A_SHARP_6=74;Hamster.NOTE_B_FLAT_6=74;Hamster.NOTE_B_6=75;Hamster.NOTE_C_7=76;Hamster.NOTE_C_SHARP_7=77;Hamster.NOTE_D_FLAT_7=77;Hamster.NOTE_D_7=78;Hamster.NOTE_D_SHARP_7=79;Hamster.NOTE_E_FLAT_7=79;Hamster.NOTE_E_7=80;Hamster.NOTE_F_7=81;Hamster.NOTE_F_SHARP_7=82;Hamster.NOTE_G_FLAT_7=82;Hamster.NOTE_G_7=83;Hamster.NOTE_G_SHARP_7=84;Hamster.NOTE_A_FLAT_7=84;Hamster.NOTE_A_7=85;Hamster.NOTE_A_SHARP_7=86;Hamster.NOTE_B_FLAT_7=86;Hamster.NOTE_B_7=87;Hamster.NOTE_C_8=88;
Hamster.create=function(){return new Hamster};
function Turtle(){var a=this,x="Turtle",m=void 0,p=0,d=1,l=void 0,t=void 0,y=void 0,q=void 0,n=void 0,r=void 0,B=[],f=[],k=[],A=[],w=[],c=[],h=[],v=ConnectionState.CONNECTING,z=0,b={bind:function(a,b,d,e){b==DeviceType.SENSOR||b==DeviceType.EVENT?(B.push(a),f.push(d.read),k.push(e)):(A.push(a),w.push(d.read),c.push(d.write),h.push(e))},onMotoringDeviceWritten:function(a){switch(a.getId()){case Turtle.PULSE:z|=67108864;break;case Turtle.NOTE:z|=33554432;break;case Turtle.SOUND:z|=16777216;break;case Turtle.LINE_TRACER_MODE:z|=
8388608;break;case Turtle.LINE_TRACER_GAIN:z|=4194304;break;case Turtle.LINE_TRACER_SPEED:z|=2097152;break;case Turtle.LAMP:z|=1048576;break;case Turtle.LOCK:z|=524288;break;case Turtle.MOTION:z|=262144}}},e={};e[Turtle.LEFT_WHEEL]=new Device(b,Turtle.LEFT_WHEEL,"LeftWheel",DeviceType.EFFECTOR,DataType.FLOAT,1,-400,400,0);e[Turtle.RIGHT_WHEEL]=new Device(b,Turtle.RIGHT_WHEEL,"RightWheel",DeviceType.EFFECTOR,DataType.FLOAT,1,-400,400,0);e[Turtle.LED]=new Device(b,Turtle.LED,"Led",DeviceType.EFFECTOR,
DataType.INTEGER,3,0,255,0);e[Turtle.BUZZER]=new Device(b,Turtle.BUZZER,"Buzzer",DeviceType.EFFECTOR,DataType.FLOAT,1,0,167772.15,0);e[Turtle.PULSE]=new Device(b,Turtle.PULSE,"Pulse",DeviceType.COMMAND,DataType.INTEGER,1,0,65535,0);e[Turtle.NOTE]=new Device(b,Turtle.NOTE,"Note",DeviceType.COMMAND,DataType.INTEGER,1,0,88,0);e[Turtle.SOUND]=new Device(b,Turtle.SOUND,"Sound",DeviceType.COMMAND,DataType.INTEGER,1,0,127,0);e[Turtle.LINE_TRACER_MODE]=new Device(b,Turtle.LINE_TRACER_MODE,"LineTracerMode",
DeviceType.COMMAND,DataType.INTEGER,1,0,127,0);e[Turtle.LINE_TRACER_GAIN]=new Device(b,Turtle.LINE_TRACER_GAIN,"LineTracerGain",DeviceType.COMMAND,DataType.INTEGER,1,1,8,5);e[Turtle.LINE_TRACER_SPEED]=new Device(b,Turtle.LINE_TRACER_SPEED,"LineTracerSpeed",DeviceType.COMMAND,DataType.INTEGER,1,1,8,5);e[Turtle.LAMP]=new Device(b,Turtle.LAMP,"Lamp",DeviceType.COMMAND,DataType.INTEGER,1,0,1,1);e[Turtle.LOCK]=new Device(b,Turtle.LOCK,"Lock",DeviceType.COMMAND,DataType.INTEGER,1,0,1,0);e[Turtle.MOTION]=
new Device(b,Turtle.MOTION,"Motion",DeviceType.COMMAND,DataType.FLOAT,5,0,2147483647,0);e[Turtle.SIGNAL_STRENGTH]=new Device(b,Turtle.SIGNAL_STRENGTH,"SignalStrength",DeviceType.SENSOR,DataType.INTEGER,1,-128,0,0);e[Turtle.COLOR]=new Device(b,Turtle.COLOR,"Color",DeviceType.SENSOR,DataType.INTEGER,4,0,255,0);e[Turtle.FLOOR]=new Device(b,Turtle.FLOOR,"Floor",DeviceType.SENSOR,DataType.INTEGER,1,0,255,0);e[Turtle.ACCELERATION]=new Device(b,Turtle.ACCELERATION,"Acceleration",DeviceType.SENSOR,DataType.INTEGER,
3,-32768,32767,0);e[Turtle.TEMPERATURE]=new Device(b,Turtle.TEMPERATURE,"Temperature",DeviceType.SENSOR,DataType.INTEGER,1,-40,88,0);e[Turtle.BUTTON]=new Device(b,Turtle.BUTTON,"Button",DeviceType.EVENT,DataType.INTEGER,1,0,1,0);e[Turtle.CLICKED]=new Device(b,Turtle.CLICKED,"Clicked",DeviceType.EVENT,DataType.INTEGER,0,0,0,0);e[Turtle.DOUBLE_CLICKED]=new Device(b,Turtle.DOUBLE_CLICKED,"DoubleClicked",DeviceType.EVENT,DataType.INTEGER,0,0,0,0);e[Turtle.LONG_PRESSED]=new Device(b,Turtle.LONG_PRESSED,
"LongPressed",DeviceType.EVENT,DataType.INTEGER,0,0,0,0);e[Turtle.COLOR_NUMBER]=new Device(b,Turtle.COLOR_NUMBER,"ColorNumber",DeviceType.EVENT,DataType.INTEGER,1,-1,8,-1);e[Turtle.COLOR_PATTERN]=new Device(b,Turtle.COLOR_PATTERN,"ColorPattern",DeviceType.EVENT,DataType.INTEGER,1,-1,88,-1);e[Turtle.PULSE_COUNT]=new Device(b,Turtle.PULSE_COUNT,"PulseCount",DeviceType.EVENT,DataType.INTEGER,1,0,65535,0);e[Turtle.WHEEL_STATE]=new Device(b,Turtle.WHEEL_STATE,"WheelState",DeviceType.EVENT,DataType.INTEGER,
1,0,1,0);e[Turtle.SOUND_STATE]=new Device(b,Turtle.SOUND_STATE,"SoundState",DeviceType.EVENT,DataType.INTEGER,1,0,1,0);e[Turtle.LINE_TRACER_STATE]=new Device(b,Turtle.LINE_TRACER_STATE,"LineTracerState",DeviceType.EVENT,DataType.INTEGER,1,0,3,0);var u={map:0,leftWheel:0,rightWheel:0,ledRed:0,ledGreen:0,ledBlue:0,buzzer:0,pulse:0,note:0,sound:0,lineTracerMode:0,lineTracerGain:5,lineTracerSpeed:5,lamp:1,lock:0,motionType:0,motionUnit:0,motionSpeed:0,motionValue:0,motionRadius:0};a.getId=function(){return"kr.robomation.physical.turtle"};
a.getName=function(){return x};a.setName=function(a){x=""+a};a.findDeviceById=function(a){if(a=e[a])return a};a.e=function(g){return(g=a.findDeviceById(g))?g.e():!1};a.read=function(g,b){var c=a.findDeviceById(g);return c?c.read(b):0};a.write=function(b,c,d){return(b=a.findDeviceById(b))?b.write(c,d):c&&c.constructor==Array?0:!1};a.addDeviceDataChangedListener=function(a){for(var b in e)e[b].addDeviceDataChangedListener(a)};a.removeDeviceDataChangedListener=function(a){for(var b in e)e[b].removeDeviceDataChangedListener(a)};
a.clearDeviceDataChangedListeners=function(){for(var a in e)e[a].clearDeviceDataChangedListeners()};var C=function(b,c){"number"!=typeof c&&(c=1);0>c&&(c=-1);c&&(p=b,d=c,a.write(Turtle.SOUND,b))},D=__runner.addRobot(a,u,{handleSensory:function(b){var c;v=b.connectionState;var g=b.map;f[0][0]=b.signalStrength;f[1][0]=b.colorRed;f[1][1]=b.colorGreen;f[1][2]=b.colorBlue;f[1][3]=b.colorClear;f[2][0]=b.floor;f[3][0]=b.accelerationX;f[3][1]=b.accelerationY;f[3][2]=b.accelerationZ;f[4][0]=b.temperature;
for(c=0;5>c;++c)k[c].fire();g&4096&&(f[5][0]=b.button,k[5].fire());g&2048&&k[6].fire();g&1024&&k[7].fire();g&512&&k[8].fire();g&256&&(f[9][0]=b.colorNumber,k[9].fire());g&128&&(f[10][0]=b.colorPattern,k[10].fire());g&64&&(f[11][0]=b.pulseCount,k[11].fire());g&32&&(f[12][0]=b.wheelState,k[12].fire());g&16&&(f[13][0]=b.soundState,k[13].fire());g&8&&(f[14][0]=b.lineTracerState,k[14].fire());for(c=0;5>c;++c)k[c].notifyDeviceDataChanged();g&4096&&k[5].notifyDeviceDataChanged();g&2048&&(k[6].notifyDeviceDataChanged(),
y&&y());g&1024&&(k[7].notifyDeviceDataChanged(),q&&q());g&512&&(k[8].notifyDeviceDataChanged(),n&&n());g&256&&k[9].notifyDeviceDataChanged();g&128&&(k[10].notifyDeviceDataChanged(),r&&r(b.colorPattern));g&64&&k[11].notifyDeviceDataChanged();g&32&&(k[12].notifyDeviceDataChanged(),0==b.wheelState&&(a.write(Turtle.LEFT_WHEEL,0),a.write(Turtle.RIGHT_WHEEL,0),c=m,m=void 0,c&&c()));g&16&&(k[13].notifyDeviceDataChanged(),0==b.soundState&&(0<p?0>d?C(p,-1):1<d?(d--,C(p,d)):(p=0,d=1,c=l,l=void 0,c&&c()):(p=
0,d=1)));g&8&&(k[14].notifyDeviceDataChanged(),2==b.lineTracerState&&(a.write(Turtle.LINE_TRACER_MODE,0),c=t,t=void 0,c&&c()))},requestMotoring:function(){var a=4160749568|z;z=0;u.map=a;u.leftWheel=c[0][0];u.rightWheel=c[1][0];u.ledRed=c[2][0];u.ledGreen=c[2][1];u.ledBlue=c[2][2];u.buzzer=c[3][0];a&67108864&&(u.pulse=c[4][0]);a&33554432&&(u.note=c[5][0]);a&16777216&&(u.sound=c[6][0]);a&8388608&&(u.lineTracerMode=c[7][0]);a&4194304&&(u.lineTracerGain=c[8][0]);a&2097152&&(u.lineTracerSpeed=c[9][0]);
a&1048576&&(u.lamp=c[10][0]);a&524288&&(u.lock=c[11][0]);a&262144&&(u.motionType=parseInt(c[12][0]),u.motionUnit=parseInt(c[12][1]),u.motionSpeed=c[12][2],u.motionValue=c[12][3],u.motionRadius=c[12][4])},updateSensory:function(){for(var a in k)k[a].update()},updateMotoring:function(){for(var a in h)h[a].update()}});a.getIndex=function(){return D};a.reset=function(){var a=h,b;for(b in a)a[b].reset();a=k;for(b in a)a[b].reset();z|=133955584;m=void 0;p=0;d=1;r=n=q=y=t=l=void 0};a.connectionState=function(){return v};
a.wheels=function(b,c){a.write(Turtle.PULSE,0);a.write(Turtle.LINE_TRACER_MODE,0);a.write(Turtle.MOTION,0);"number"==typeof b&&a.write(Turtle.LEFT_WHEEL,b);"number"==typeof c?a.write(Turtle.RIGHT_WHEEL,c):"number"==typeof b&&a.write(Turtle.RIGHT_WHEEL,b)};a.leftWheel=function(b){a.write(Turtle.PULSE,0);a.write(Turtle.LINE_TRACER_MODE,0);a.write(Turtle.MOTION,0);"number"==typeof b&&a.write(Turtle.LEFT_WHEEL,b)};a.rightWheel=function(b){a.write(Turtle.PULSE,0);a.write(Turtle.LINE_TRACER_MODE,0);a.write(Turtle.MOTION,
0);"number"==typeof b&&a.write(Turtle.RIGHT_WHEEL,b)};a.moveForward=function(b,c,d){a.write(Turtle.LEFT_WHEEL,0);a.write(Turtle.RIGHT_WHEEL,0);a.write(Turtle.PULSE,0);a.write(Turtle.LINE_TRACER_MODE,0);var g=0,e=void 0;"number"==typeof c?(g=c,"function"==typeof d&&(e=d)):"function"==typeof c&&(e=c);"number"==typeof b&&0<=g&&(m=e,a.write(Turtle.MOTION,1,1),a.write(Turtle.MOTION,2,g),0>b?(a.write(Turtle.MOTION,3,-b),a.write(Turtle.MOTION,0,2)):(a.write(Turtle.MOTION,3,b),a.write(Turtle.MOTION,0,1)))};
a.moveBackward=function(b,c,d){a.write(Turtle.LEFT_WHEEL,0);a.write(Turtle.RIGHT_WHEEL,0);a.write(Turtle.PULSE,0);a.write(Turtle.LINE_TRACER_MODE,0);var g=0,e=void 0;"number"==typeof c?(g=c,"function"==typeof d&&(e=d)):"function"==typeof c&&(e=c);"number"==typeof b&&0<=g&&(m=e,a.write(Turtle.MOTION,1,1),a.write(Turtle.MOTION,2,g),0>b?(a.write(Turtle.MOTION,3,-b),a.write(Turtle.MOTION,0,1)):(a.write(Turtle.MOTION,3,b),a.write(Turtle.MOTION,0,2)))};a.turnLeft=function(b,c,d){a.write(Turtle.LEFT_WHEEL,
0);a.write(Turtle.RIGHT_WHEEL,0);a.write(Turtle.PULSE,0);a.write(Turtle.LINE_TRACER_MODE,0);var g=0,e=void 0;"number"==typeof c?(g=c,"function"==typeof d&&(e=d)):"function"==typeof c&&(e=c);"number"==typeof b&&0<=g&&(m=e,a.write(Turtle.MOTION,1,1),a.write(Turtle.MOTION,2,g),0>b?(a.write(Turtle.MOTION,3,-b),a.write(Turtle.MOTION,0,4)):(a.write(Turtle.MOTION,3,b),a.write(Turtle.MOTION,0,3)))};a.turnRight=function(b,c,d){a.write(Turtle.LEFT_WHEEL,0);a.write(Turtle.RIGHT_WHEEL,0);a.write(Turtle.PULSE,
0);a.write(Turtle.LINE_TRACER_MODE,0);var g=0,e=void 0;"number"==typeof c?(g=c,"function"==typeof d&&(e=d)):"function"==typeof c&&(e=c);"number"==typeof b&&0<=g&&(m=e,a.write(Turtle.MOTION,1,1),a.write(Turtle.MOTION,2,g),0>b?(a.write(Turtle.MOTION,3,-b),a.write(Turtle.MOTION,0,3)):(a.write(Turtle.MOTION,3,b),a.write(Turtle.MOTION,0,4)))};a.pivotLeft=function(b,c,d){a.write(Turtle.LEFT_WHEEL,0);a.write(Turtle.RIGHT_WHEEL,0);a.write(Turtle.PULSE,0);a.write(Turtle.LINE_TRACER_MODE,0);var g=0,e=void 0;
"number"==typeof c?(g=c,"function"==typeof d&&(e=d)):"function"==typeof c&&(e=c);"number"==typeof b&&0<=g&&(m=e,a.write(Turtle.MOTION,1,1),a.write(Turtle.MOTION,2,g),0>b?(a.write(Turtle.MOTION,3,-b),a.write(Turtle.MOTION,0,6)):(a.write(Turtle.MOTION,3,b),a.write(Turtle.MOTION,0,5)))};a.pivotRight=function(b,c,d){a.write(Turtle.LEFT_WHEEL,0);a.write(Turtle.RIGHT_WHEEL,0);a.write(Turtle.PULSE,0);a.write(Turtle.LINE_TRACER_MODE,0);var g=0,e=void 0;"number"==typeof c?(g=c,"function"==typeof d&&(e=d)):
"function"==typeof c&&(e=c);"number"==typeof b&&0<=g&&(m=e,a.write(Turtle.MOTION,1,1),a.write(Turtle.MOTION,2,g),0>b?(a.write(Turtle.MOTION,3,-b),a.write(Turtle.MOTION,0,8)):(a.write(Turtle.MOTION,3,b),a.write(Turtle.MOTION,0,7)))};a.swingLeft=function(b,c,d,e){a.write(Turtle.LEFT_WHEEL,0);a.write(Turtle.RIGHT_WHEEL,0);a.write(Turtle.PULSE,0);a.write(Turtle.LINE_TRACER_MODE,0);var g=0,f=void 0;"number"==typeof d?(g=d,"function"==typeof e&&(f=e)):"function"==typeof d&&(f=d);"number"==typeof b&&"number"==
typeof c&&0<=c&&0<=g&&(m=f,a.write(Turtle.MOTION,1,1),a.write(Turtle.MOTION,2,g),a.write(Turtle.MOTION,4,c),0>b?(a.write(Turtle.MOTION,3,-b),a.write(Turtle.MOTION,0,10)):(a.write(Turtle.MOTION,3,b),a.write(Turtle.MOTION,0,9)))};a.swingRight=function(b,c,d,e){a.write(Turtle.LEFT_WHEEL,0);a.write(Turtle.RIGHT_WHEEL,0);a.write(Turtle.PULSE,0);a.write(Turtle.LINE_TRACER_MODE,0);var g=0,f=void 0;"number"==typeof d?(g=d,"function"==typeof e&&(f=e)):"function"==typeof d&&(f=d);"number"==typeof b&&"number"==
typeof c&&0<=c&&0<=g&&(m=f,a.write(Turtle.MOTION,1,1),a.write(Turtle.MOTION,2,g),a.write(Turtle.MOTION,4,c),0>b?(a.write(Turtle.MOTION,3,-b),a.write(Turtle.MOTION,0,12)):(a.write(Turtle.MOTION,3,b),a.write(Turtle.MOTION,0,11)))};a.pulse=function(b,c,d,e){a.write(Turtle.LINE_TRACER_MODE,0);a.write(Turtle.MOTION,0);var g=void 0;if("number"==typeof d){var f=d;"function"==typeof e&&(g=e)}else f=c,"function"==typeof d&&(g=d);"number"==typeof b&&"number"==typeof c&&"number"==typeof f&&(a.write(Turtle.LEFT_WHEEL,
c),a.write(Turtle.RIGHT_WHEEL,f),0<b?(m=g,a.write(Turtle.PULSE,b)):(a.write(Turtle.PULSE,0),g&&g()))};a.stop=function(){a.write(Turtle.LEFT_WHEEL,0);a.write(Turtle.RIGHT_WHEEL,0);a.write(Turtle.PULSE,0);a.write(Turtle.LINE_TRACER_MODE,0);a.write(Turtle.MOTION,0)};a.lineTracerMode=function(b,c){a.write(Turtle.LEFT_WHEEL,0);a.write(Turtle.RIGHT_WHEEL,0);a.write(Turtle.PULSE,0);a.write(Turtle.MOTION,0);if("number"==typeof b){switch(b){case Turtle.LINE_TRACER_MODE_TURN_LEFT:case Turtle.LINE_TRACER_MODE_TURN_RIGHT:case Turtle.LINE_TRACER_MODE_CROSS:case Turtle.LINE_TRACER_MODE_UTURN:case Turtle.LINE_TRACER_MODE_BLACK_UNTIL_RED:case Turtle.LINE_TRACER_MODE_BLACK_UNTIL_YELLOW:case Turtle.LINE_TRACER_MODE_BLACK_UNTIL_GREEN:case Turtle.LINE_TRACER_MODE_BLACK_UNTIL_CYAN:case Turtle.LINE_TRACER_MODE_BLACK_UNTIL_BLUE:case Turtle.LINE_TRACER_MODE_BLACK_UNTIL_MAGENTA:case Turtle.LINE_TRACER_MODE_BLACK_UNTIL_ANY:case Turtle.LINE_TRACER_MODE_RED_UNTIL_BLACK:case Turtle.LINE_TRACER_MODE_GREEN_UNTIL_BLACK:case Turtle.LINE_TRACER_MODE_BLUE_UNTIL_BLACK:case Turtle.LINE_TRACER_MODE_ANY_UNTIL_BLACK:c&&
"function"==typeof c&&(t=c)}a.write(Turtle.LINE_TRACER_MODE,b)}};a.lineTracerGain=function(b){"number"==typeof b&&a.write(Turtle.LINE_TRACER_GAIN,b)};a.lineTracerSpeed=function(b){"number"==typeof b&&a.write(Turtle.LINE_TRACER_SPEED,b)};a.led=function(b,c,d){"number"==typeof b&&a.write(Turtle.LED,0,b);"number"==typeof c&&"number"==typeof d?(a.write(Turtle.LED,1,c),a.write(Turtle.LED,2,d)):"number"==typeof b&&(a.write(Turtle.LED,1,b),a.write(Turtle.LED,2,b))};a.buzzer=function(b){"number"==typeof b&&
a.write(Turtle.BUZZER,b);a.write(Turtle.NOTE,0);C(0)};a.note=function(b){a.write(Turtle.BUZZER,0);"number"==typeof b&&a.write(Turtle.NOTE,b);C(0)};a.sound=function(b,c,d){a.write(Turtle.BUZZER,0);a.write(Turtle.NOTE,0);if("number"==typeof b){var e=1,f=void 0;"number"==typeof c?(e=c,"function"==typeof d&&(f=d)):"function"==typeof c&&(f=c);e?(l=f,C(b,e)):f&&f()}};a.lamp=function(b){"number"==typeof b&&a.write(Turtle.LAMP,b)};a.lock=function(b){"number"==typeof b&&a.write(Turtle.LOCK,b)};a.signalStrength=
function(){return a.read(Turtle.SIGNAL_STRENGTH)};a.floor=function(){return a.read(Turtle.FLOOR)};a.accelerationX=function(){return a.read(Turtle.ACCELERATION,0)};a.accelerationY=function(){return a.read(Turtle.ACCELERATION,1)};a.accelerationZ=function(){return a.read(Turtle.ACCELERATION,2)};a.temperature=function(){return a.read(Turtle.TEMPERATURE)};a.button=function(){return a.read(Turtle.BUTTON)};a.clicked=function(b){"function"==typeof b&&(y=b);return a.e(Turtle.CLICKED)};a.doubleClicked=function(b){"function"==
typeof b&&(q=b);return a.e(Turtle.DOUBLE_CLICKED)};a.longPressed=function(b){"function"==typeof b&&(n=b);return a.e(Turtle.LONG_PRESSED)};a.colorNumber=function(){return a.read(Turtle.COLOR_NUMBER)};a.colorPattern=function(b){"function"==typeof b&&(r=b);return a.e(Turtle.COLOR_PATTERN)?a.read(Turtle.COLOR_PATTERN):-1};a.pulseCount=function(){return a.read(Turtle.PULSE_COUNT)}}Turtle.ID="kr.robomation.physical.turtle";Turtle.LEFT_WHEEL=9437184;Turtle.RIGHT_WHEEL=9437185;Turtle.LED=9437186;
Turtle.BUZZER=9437187;Turtle.PULSE=9437188;Turtle.NOTE=9437189;Turtle.SOUND=9437190;Turtle.LINE_TRACER_MODE=9437191;Turtle.LINE_TRACER_GAIN=9437192;Turtle.LINE_TRACER_SPEED=9437193;Turtle.LAMP=9437194;Turtle.LOCK=9437195;Turtle.MOTION=9437196;Turtle.SIGNAL_STRENGTH=9437197;Turtle.COLOR=9437198;Turtle.FLOOR=9437199;Turtle.ACCELERATION=9437200;Turtle.TEMPERATURE=9437201;Turtle.BUTTON=9437202;Turtle.CLICKED=9437203;Turtle.DOUBLE_CLICKED=9437204;Turtle.LONG_PRESSED=9437205;Turtle.COLOR_NUMBER=9437206;
Turtle.COLOR_PATTERN=9437207;Turtle.PULSE_COUNT=9437208;Turtle.WHEEL_STATE=9437209;Turtle.SOUND_STATE=9437210;Turtle.LINE_TRACER_STATE=9437211;Turtle.COLOR_NONE=-1;Turtle.COLOR_BLACK=0;Turtle.COLOR_RED=1;Turtle.COLOR_ORANGE=2;Turtle.COLOR_YELLOW=3;Turtle.COLOR_GREEN=4;Turtle.COLOR_CYAN=5;Turtle.COLOR_BLUE=6;Turtle.COLOR_MAGENTA=7;Turtle.COLOR_WHITE=8;Turtle.LINE_TRACER_MODE_OFF=0;Turtle.LINE_TRACER_MODE_BLACK=10;Turtle.LINE_TRACER_MODE_RED=11;Turtle.LINE_TRACER_MODE_GREEN=13;
Turtle.LINE_TRACER_MODE_BLUE=15;Turtle.LINE_TRACER_MODE_ANY=17;Turtle.LINE_TRACER_MODE_TURN_LEFT=20;Turtle.LINE_TRACER_MODE_TURN_RIGHT=30;Turtle.LINE_TRACER_MODE_CROSS=40;Turtle.LINE_TRACER_MODE_UTURN=50;Turtle.LINE_TRACER_MODE_BLACK_UNTIL_RED=61;Turtle.LINE_TRACER_MODE_BLACK_UNTIL_YELLOW=62;Turtle.LINE_TRACER_MODE_BLACK_UNTIL_GREEN=63;Turtle.LINE_TRACER_MODE_BLACK_UNTIL_CYAN=64;Turtle.LINE_TRACER_MODE_BLACK_UNTIL_BLUE=65;Turtle.LINE_TRACER_MODE_BLACK_UNTIL_MAGENTA=66;
Turtle.LINE_TRACER_MODE_BLACK_UNTIL_ANY=67;Turtle.LINE_TRACER_MODE_RED_UNTIL_BLACK=71;Turtle.LINE_TRACER_MODE_GREEN_UNTIL_BLACK=73;Turtle.LINE_TRACER_MODE_BLUE_UNTIL_BLACK=75;Turtle.LINE_TRACER_MODE_ANY_UNTIL_BLACK=77;Turtle.NOTE_OFF=0;Turtle.NOTE_A_0=1;Turtle.NOTE_A_SHARP_0=2;Turtle.NOTE_B_FLAT_0=2;Turtle.NOTE_B_0=3;Turtle.NOTE_C_1=4;Turtle.NOTE_C_SHARP_1=5;Turtle.NOTE_D_FLAT_1=5;Turtle.NOTE_D_1=6;Turtle.NOTE_D_SHARP_1=7;Turtle.NOTE_E_FLAT_1=7;Turtle.NOTE_E_1=8;Turtle.NOTE_F_1=9;
Turtle.NOTE_F_SHARP_1=10;Turtle.NOTE_G_FLAT_1=10;Turtle.NOTE_G_1=11;Turtle.NOTE_G_SHARP_1=12;Turtle.NOTE_A_FLAT_1=12;Turtle.NOTE_A_1=13;Turtle.NOTE_A_SHARP_1=14;Turtle.NOTE_B_FLAT_1=14;Turtle.NOTE_B_1=15;Turtle.NOTE_C_2=16;Turtle.NOTE_C_SHARP_2=17;Turtle.NOTE_D_FLAT_2=17;Turtle.NOTE_D_2=18;Turtle.NOTE_D_SHARP_2=19;Turtle.NOTE_E_FLAT_2=19;Turtle.NOTE_E_2=20;Turtle.NOTE_F_2=21;Turtle.NOTE_F_SHARP_2=22;Turtle.NOTE_G_FLAT_2=22;Turtle.NOTE_G_2=23;Turtle.NOTE_G_SHARP_2=24;Turtle.NOTE_A_FLAT_2=24;
Turtle.NOTE_A_2=25;Turtle.NOTE_A_SHARP_2=26;Turtle.NOTE_B_FLAT_2=26;Turtle.NOTE_B_2=27;Turtle.NOTE_C_3=28;Turtle.NOTE_C_SHARP_3=29;Turtle.NOTE_D_FLAT_3=29;Turtle.NOTE_D_3=30;Turtle.NOTE_D_SHARP_3=31;Turtle.NOTE_E_FLAT_3=31;Turtle.NOTE_E_3=32;Turtle.NOTE_F_3=33;Turtle.NOTE_F_SHARP_3=34;Turtle.NOTE_G_FLAT_3=34;Turtle.NOTE_G_3=35;Turtle.NOTE_G_SHARP_3=36;Turtle.NOTE_A_FLAT_3=36;Turtle.NOTE_A_3=37;Turtle.NOTE_A_SHARP_3=38;Turtle.NOTE_B_FLAT_3=38;Turtle.NOTE_B_3=39;Turtle.NOTE_C_4=40;
Turtle.NOTE_C_SHARP_4=41;Turtle.NOTE_D_FLAT_4=41;Turtle.NOTE_D_4=42;Turtle.NOTE_D_SHARP_4=43;Turtle.NOTE_E_FLAT_4=43;Turtle.NOTE_E_4=44;Turtle.NOTE_F_4=45;Turtle.NOTE_F_SHARP_4=46;Turtle.NOTE_G_FLAT_4=46;Turtle.NOTE_G_4=47;Turtle.NOTE_G_SHARP_4=48;Turtle.NOTE_A_FLAT_4=48;Turtle.NOTE_A_4=49;Turtle.NOTE_A_SHARP_4=50;Turtle.NOTE_B_FLAT_4=50;Turtle.NOTE_B_4=51;Turtle.NOTE_C_5=52;Turtle.NOTE_C_SHARP_5=53;Turtle.NOTE_D_FLAT_5=53;Turtle.NOTE_D_5=54;Turtle.NOTE_D_SHARP_5=55;Turtle.NOTE_E_FLAT_5=55;
Turtle.NOTE_E_5=56;Turtle.NOTE_F_5=57;Turtle.NOTE_F_SHARP_5=58;Turtle.NOTE_G_FLAT_5=58;Turtle.NOTE_G_5=59;Turtle.NOTE_G_SHARP_5=60;Turtle.NOTE_A_FLAT_5=60;Turtle.NOTE_A_5=61;Turtle.NOTE_A_SHARP_5=62;Turtle.NOTE_B_FLAT_5=62;Turtle.NOTE_B_5=63;Turtle.NOTE_C_6=64;Turtle.NOTE_C_SHARP_6=65;Turtle.NOTE_D_FLAT_6=65;Turtle.NOTE_D_6=66;Turtle.NOTE_D_SHARP_6=67;Turtle.NOTE_E_FLAT_6=67;Turtle.NOTE_E_6=68;Turtle.NOTE_F_6=69;Turtle.NOTE_F_SHARP_6=70;Turtle.NOTE_G_FLAT_6=70;Turtle.NOTE_G_6=71;
Turtle.NOTE_G_SHARP_6=72;Turtle.NOTE_A_FLAT_6=72;Turtle.NOTE_A_6=73;Turtle.NOTE_A_SHARP_6=74;Turtle.NOTE_B_FLAT_6=74;Turtle.NOTE_B_6=75;Turtle.NOTE_C_7=76;Turtle.NOTE_C_SHARP_7=77;Turtle.NOTE_D_FLAT_7=77;Turtle.NOTE_D_7=78;Turtle.NOTE_D_SHARP_7=79;Turtle.NOTE_E_FLAT_7=79;Turtle.NOTE_E_7=80;Turtle.NOTE_F_7=81;Turtle.NOTE_F_SHARP_7=82;Turtle.NOTE_G_FLAT_7=82;Turtle.NOTE_G_7=83;Turtle.NOTE_G_SHARP_7=84;Turtle.NOTE_A_FLAT_7=84;Turtle.NOTE_A_7=85;Turtle.NOTE_A_SHARP_7=86;Turtle.NOTE_B_FLAT_7=86;
Turtle.NOTE_B_7=87;Turtle.NOTE_C_8=88;Turtle.SOUND_OFF=0;Turtle.SOUND_BEEP=1;Turtle.SOUND_RANDOM=2;Turtle.SOUND_SIREN=3;Turtle.SOUND_ENGINE=4;Turtle.SOUND_ROBOT=5;Turtle.SOUND_MARCH=6;Turtle.SOUND_BIRTHDAY=7;Turtle.SOUND_DIBIDIBIDIP=8;Turtle.SOUND_GOOD_JOB=9;Turtle.MOTION_NONE=0;Turtle.MOTION_MOVE_FORWARD=1;Turtle.MOTION_MOVE_BACKWARD=2;Turtle.MOTION_TURN_LEFT=3;Turtle.MOTION_TURN_RIGHT=4;Turtle.MOTION_PIVOT_LEFT_HEAD=5;Turtle.MOTION_PIVOT_LEFT_TAIL=6;Turtle.MOTION_PIVOT_RIGHT_HEAD=7;
Turtle.MOTION_PIVOT_RIGHT_TAIL=8;Turtle.MOTION_SWING_LEFT_HEAD=9;Turtle.MOTION_SWING_LEFT_TAIL=10;Turtle.MOTION_SWING_RIGHT_HEAD=11;Turtle.MOTION_SWING_RIGHT_TAIL=12;Turtle.UNIT_NONE=0;Turtle.UNIT_CM_DEG=1;Turtle.UNIT_SEC=2;Turtle.UNIT_PULSE=3;Turtle.create=function(){return new Turtle};